version: "3"
services:
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "81:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webnet
    keycloak:
        image: jboss/keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - PROXY_ADDRESS_FORWARDING=true
        networks:
            - webnet
    db:
        image: library/postgres:latest
        environment:
            - POSTGRES_USER=registration
            - POSTGRES_PASSWORD=registration
            - POSTGRES_DB=registration
        networks:
            - webnet
    registration:
        build: ./registration
        image: "567106281522.dkr.ecr.eu-central-1.amazonaws.com/hackathon/registration:latest"
        environment:
            - KEYCLOAK_AUTH_SERVER=http://ec2-35-158-93-72.eu-central-1.compute.amazonaws.com/auth
        depends_on:
            - db
        deploy:
            replicas: 2
        networks:
            - webnet
    questions:
        build: ./questions/docker
        image: "567106281522.dkr.ecr.eu-central-1.amazonaws.com/hackathon/questions:latest"
        networks:
            - webnet
    reverseproxy:
        build: ./reverse-proxy
        image: "567106281522.dkr.ecr.eu-central-1.amazonaws.com/hackaton/reverse_proxy:latest"
        depends_on:
            - registration
            - questions
            - keycloak
        ports:
            - "80:80"
        networks:
            - webnet
networks:
    webnet:
