version: "3"
services:
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "81:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webnet
    keycloak:
        image: jboss/keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        networks:
            - webnet
    db:
        image: library/postgres:latest
            - "5432:5432"
        environment:
            - POSTGRES_USER=registration
            - POSTGRES_PASSWORD=registration
            - POSTGRES_DB=registration
        networks:
            - webnet
    registration:
        image: "567106281522.dkr.ecr.eu-central-1.amazonaws.com/hackathon/registration:latest"
        networks:
            - webnet
    questions:
        image: "567106281522.dkr.ecr.eu-central-1.amazonaws.com/hackathon/questions:latest"
        ports:
            - "5000:80"
    reverseproxy:
        image: "567106281522.dkr.ecr.eu-central-1.amazonaws.com/hackaton/reverse_proxy:latest"
        ports:
            - "80:80"
        networks:
            - webnet
networks:
    webnet:
